version: '3'

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
    env_file:
      - env.db
    network_mode: bridge

  redis:
    image: redis:5-alpine
    restart: always
    network_mode: bridge

  app:
    build: nextcloud
    container_name: nextcloud
    restart: always
    expose:
      - 80
    volumes:
      - /home/dave/storage:/var/www/html
    environment:
      - MYSQL_HOST=db
    env_file:
      - env.db
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    labels:
      - traefik.backend=cloud
      - traefik.frontend.rule=Host:cloud.TODO.url
    network_mode: bridge

  cron:
    build: cron
    restart: always
    links:
      - app
    depends_on:
      - app
    network_mode: bridge

volumes:
  db:

